name: fast_structure
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.6 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  auto_size_text: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  adaptive_theme: ^3.4.1
  flutter_dotenv: ^5.1.0
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  fk_user_agent: ^2.1.0
  path_provider: ^2.1.1
  flutter_screenutil: ^5.9.0
  animate_do: ^3.1.2
  lottie: ^2.6.0
  google_fonts: ^5.1.0
  flutter_keyboard_visibility: ^5.4.1
  pinput: ^3.0.1
  keyboard_actions: ^4.2.0
  permission_handler: ^11.0.1
  another_flushbar: ^1.12.30
  stacked: ^3.4.1+1
  flutter_svg: ^2.0.9
  get_it: ^7.6.4
  intl: ^0.18.1
  smooth_page_indicator: ^1.1.0
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  rate_in_stars: ^0.0.3
  map_launcher: ^3.1.0
  flutter_sound: ^9.2.13
  image_picker: ^1.0.5
  audio_session: ^0.1.18
  audio_waveforms: ^1.0.4
  
  #Vexana
  collection: ^1.17.1
  connectivity_plus: ^5.0.2
  dio: ^5.3.1
  logger: ^1.1.0
  retry: ^3.1.0
  sembast: ^3.3.1+1
  sembast_web: ^2.0.1+1
  shared_preferences: ^2.0.3
  sms_autofill: ^2.3.0
  firebase_core: ^2.16.0
  firebase_messaging: ^14.6.8
  flutter_local_notifications: ^16.1.0
  package_info_plus: ^4.2.0
  store_redirect: ^2.0.1
  mask_text_input_formatter: ^2.7.0
  sentry_flutter: ^7.15.0
  url_launcher: ^6.2.4
  typewritertext: ^2.3.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen_runner:
  mockito: ^5.0.0
  path_provider_platform_interface: ^2.0.1
  plugin_platform_interface: ^2.0.0
  build_runner: 2.3.3
  hive_generator: ^2.0.1
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/
    - assets/flags/
    - assets/audio/
    - assets/images/
    - assets/lottie/
    - assets/svg/
    - assets/pdf/
    - assets/json/
    - assets/example/
    - lib/lang/
